### ISSUE TITLE
What data can you get in Godot?

### ISSUE THREAD

**Issue by NotAFlyingGoose** [TheSleepyKoala/Svelcordot#1]
Is it possible to get data like the user id, guild id, everyone else in the call etc?

**Comment by Chizaruu** [comment]
> Is it possible to get data like the user id, guild id, everyone else in the call etc?

Of course! You can use HTTP requests to handle Discord's API directly within Godot or a bridge-like solution like [Dissonity](https://github.com/Furnyr/Dissonity) and[ nested-messages](https://github.com/discord/embedded-app-sdk-examples/tree/main/nested-messages). (Nothing exists for Godot atm)

This repository focused more on getting a developer's Godot game onto Discord Activity so that it could be played in a single-player capacity.

I would love to offer a .NET Nuget Package that allows you to skip the embedded SDK and do everything within Godot, leaving the JS side mostly untouched. However, Discord hasn't provided any Open API specs I can use to make/update it, so we are out of luck for now. :c
